.\" -*-nroff-*-
.\"
.\" glastreeprune.1
.\"
.\"  Jeremy Wohl (http://igmus.org/code)
.\"  Public domain; no warranty, no responsibility, etc.
.\"
.\"  $Id: glastreeprune.1,v 1.3 2002/06/30 22:23:37 jeremyw Exp $
.\"
.TH glastreeprune 1 "February 2002" Unix "User Manuals"
.SH NAME
.PP
glastreeprune \- list old paths in a glastree directory
.SH SYNOPSIS
.PP
.B glastreeprune
[options]
backupdir
.SH DESCRIPTION
.PP
Print date paths from a glastree backup directory, one per line, that are
older than
.I days

Combine with xargs & rm to effect a constant, sliding backup window.
.SH EXAMPLE
.PP
.nf
  # glastreeprune --days=8 /bak | xargs -- rm -fr
.fi
.SH OPTIONS
.PP
.IP "--days=\fIn\fP"
Keep last n days (from today); default is 30
.IP "--print0"
Separate lines by NUL, preserving embedded newlines
.IP "--help"
Display help message and exit
.SH REPORTING BUGS
Report bugs to <jeremyw-glastree@igmus.org>.
.SH SEE ALSO
.PP
.BR glastree (1),
.BR xargs (1)
.PP
http://igmus.org/code
.SH AUTHOR
.PP
Jeremy Wohl
