#!/usr/bin/perl

#
# glastree -- build dated, versioned tree of sourcedir, usually per diem
#
#  Jeremy Wohl (http://igmus.org/code)
#  Public domain; no warranty, no responsibility, etc.
#
#  $Id: glastree,v 1.4 2001/11/26 10:12:27 jeremyw Exp $
#

use English;
use DirHandle;
use File::Copy;
use File::stat;
use Date::Calc qw (Today Add_Delta_Days);

main ();

sub main
{
    if (not defined @ARGV or scalar @ARGV < 2)
    {
	print STDERR "usage: glastree sourcedir backupdir\n\n";
	#print STDERR "  -d n        Prune days (or directories) more than n back\n";
	#print STDERR "  -i          Use hour/minute in directory names, suppress per diem\n";
	exit 1;
    }

    $source = $ARGV [0];
    $target = $ARGV [1];

    $today     = sprintf "%4d/%02d/%02d", Today ();
    $yesterday = sprintf "%4d/%02d/%02d", Add_Delta_Days (Today (), -1);

    die "fatal: $target does not exist"                       if not -e "$target";
    die "fatal: $source does not exist"                       if not -e "$source";
    die "fatal: $target/$today already exists"                if     -e "$target/$today";
    die "fatal: you do not have read permission in $source"   if not -r "$source";
    die "fatal: you do not have write permission in $target"  if not -w "$target";
    die "fatal: backupdir is the same as sourcedir"           if $target eq $source;

    rmkdir ("$target/$today");

    recurse ($source);
}


sub recurse
{
    my ($cwd) = @_;
    my ($dir, @list, @dirs, @files);
    my ($file, $num);


    $dir   = new DirHandle ($cwd);
    @list  = $dir->read;
    @dirs  = grep { /^[^\.]/ && -d "$cwd/$_" } @list;
    @files = grep {             -f "$cwd/$_" } @list;
    undef $dir;

    # for all files in the source tree
    #   if the file is a link, make the link
    #   else if the file is a dir, make the dir
    #   else if the file is a normal file
    #     if yesterday does not exist or today is newer, copy the file
    #     else hard link the file to yesterday
    #   else: no logic to handle file type
    # end

    rmkdir ("$target/$today/$cwd");

    foreach $file (@files)
    {
	if (-l "$cwd/$file") {
	    symlink (readlink ("$cwd/$file"), "$target/$today/$cwd/$file");
	}

	elsif (-d "$cwd/$file") {
	    rmkdir ("$target/$today/$cwd/$file");
	    # set perms/ownership
	}

	elsif (-f "$cwd/$file") {
	    $now_stat = stat "$cwd/$file";
	    $yes_stat = stat "$target/$yesterday/$cwd/$file";

	    if (not defined ($yes_stat)
		or $now_stat->mtime != $yes_stat->mtime
		or $now_stat->size  != $yes_stat->size)
	    {
		copy ("$cwd/$file", "$target/$today/$cwd/$file");
		utime $now_stat->mtime, $now_stat->mtime, "$target/$today/$cwd/$file";
	    }
	    else
	    {
		link ("$target/$yesterday/$cwd/$file", "$target/$today/$cwd/$file");
	    }
	}	    

	else {
	    print STDERR "warning: no logic to handle $cwd/$file; skipping\n";
	}
    }

    foreach (@dirs) { recurse ("$cwd/$_"); }
}


#
# Make all segments of $path that do not exist
#
#
sub rmkdir ($path)
{
    my ($path) = @_;
    my ($piece, $newdir);

    foreach $piece (split '/', $path) {
	next if $piece eq "";
	$newdir .= "/" . $piece;
	mkdir $newdir, 0755 if not -e $newdir;
    }
}
